version: "3.8"
services:
  jav:
    restart: always
    image: jav
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=""
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"