version: "3.8"
services:
  jav:
    restart: always
    image: jav
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"